### ISSUE TITLE
Not an issue, just some usage questions.

### ISSUE THREAD

**Issue by XanCraft21** [LMP88959/PL3D-KC#6]
Hello, sorry to waste an issue, i just had some questions about your library.

Is it possible to use your code on a platform that’s not really made for it, like Arduino IDE. I planned to use this library on a strong microcontroller for 3D game development.

I wanted to create my own display driver and input device myself. I may need to modify the model importer code to work with my platform. My display only uses 16-bit graphics instead of the standard 24-bit, so do i need to make some modifications to the library myself to achieve this goal?

How easy is it to port this code to an unusual platform? Thank you for the help and taking the time to read this.

**Comment by LMP88959** [comment]
Hey! No problem, yes of course you can use it for really any platform. The only modifications you will need to make to get 16-bit graphics are to gfx.c where you will need to change the PL_video_buffer type to short * instead of int * and change the polygon rendering and packrgb() functions to create 16-bit packed RGBs in the format you support (e.g change                     *vbuf = mul8[d][r8] << 16 | mul8[d][g8] << 8 | mul8[d][b8] to                     *vbuf = mul8[d][r8] << 10 | mul8[d][g8] << 5 mul8[d][b8] or something).

As for the input device, the pkb.c file in the fw/ directory is universal and does not depend on an operating system, but it can be removed entirely. The main.c file contains calls to it to check for input and whatever but you can change that to poll the inputs that you have available.
Regarding the display, the simplest method to implement your own backend will be to copy fw/xvid.c and replace the function bodies with stuff that pertains to your platform. Make sure the video pointer in the VIDINFO struct gets set properly to your video memory so that the PL gfx code can properly render into it.

If you have any more questions please feel free to ask me here.

**Comment by XanCraft21** [comment]
Thank you very much for the help. I have another question about the display drivers. Is it possible to just use an array in ram as my video buffer without needing to use code from the fw folder?

**Comment by LMP88959** [comment]
Yes you can use any array, the fw folder just handles OS specific stuff like creating a window with a video buffer to draw into, input handling, etc. So as long as you have alternatives for it on your platform you can be completely independent of the fw folder.

**Comment by XanCraft21** [comment]
Thank you very much for the help. I will come back here if i need any more help.

**Comment by XanCraft21** [comment]
I have encountered a bug, and i’m not sure if it’s on my end or not. If i draw a textured cube it appears to skip every other pixel when rendered, making the image look stretched and have gaps in each vertical line.

There is also some weirdness with the rotation. It mostly wants to stay straight as if the angle is set to 0, but sometimes the triangles glitch very briefly.

Do you know how i can fix it? Thank you for your help.

**Comment by LMP88959** [comment]
I would recommend tinkering with the desktop PC version first so you can see the expected behavior.
But from the description you gave me about the image, I think you may have forgotten to change the type of the video buffer pointer from int to short in the drawing functions.

I'm not sure about the rotation issue, but like I said I recommend building and running the desktop PC version so you can see how it should look and behave so you can compare it to the one you're adapting to your platform.

**Comment by XanCraft21** [comment]
Ok, I currently don’t have the software set up to run the pc version, and it may take me a while to get it set up.

Also i did change the video buffer type to short, and i even changed another variable to short that i saw was added to the video buffer variable in the bottom 2 functions. The second part may have been unnecessary.

There is some other stuff i forgot to explain, i took snippets from the demo code main.c and designed my own code based off it.

Am i unsure what format the texturing uses, i used solid 16-bit values for the texture. Are the values meant to be split into separate bytes (Eg instead of one pixel being 0xffff, should it be 0xff, 0xff?)

For the rotation i have a single value i increment every frame with a speed balancer, which i have disable for now. I’m not sure if the rotation function is accepting that value correctly.

Another thing i forgot to mention, the int values on my platform are 16-bit, not 32-bit.

If you need me to send a video of my issue i don’t know how to do it here, so if you have discord i can send it there.

**Comment by LMP88959** [comment]
Yeah I have discord. Link is in the readme. 

Texture data is in the same format as the video originally was (packed 32-bit RGB). You will likely need to modify this and the table lookup with the >> 16 & 0xff as well since that breaks up the texel into R, G, B assuming 8 bits per channel.

16-bit ints will be annoying to work with and will require a bit of modification. You'll need to be relatively familiar with how things work in the code. The code isn't too much though so it's definitely achievable but you really should have a PC version running first with all of your 16-bit modifications made so you can verify it works before porting it.

**Comment by XanCraft21** [comment]
Ok. I will need you to help me get the pc stuff setup. I will move it to discord if that’s ok. Would you prefer if i contact you directly or join your server?

**Comment by LMP88959** [comment]
Join the server please, there are others that could help as well.

**Comment by XanCraft21** [comment]
I have joined, thank you for the help again.
